newrelic/nri-postgresql

CHANGELOG.md
src/postgresql.go

Bumped version for GA to 1.0.0.

Bumped version for GA

---

CHANGELOG.md
src/metrics/metrics.go
src/metrics/version_test.go
src/postgresql.go

Added special parsing for Ubuntu versions.
Fixes #15

Added special parsing for Ubuntu versions

---

CHANGELOG.md
postgresql-definition.yml
src/metrics/metrics.go
src/metrics/version_test.go
src/postgresql.go

- Bumped the Definition Protocol version to 2
- Added version parsing for Debian to resolves #15 again

Bumped protocol version in definition file. Fixed debian version parsing

---

CHANGELOG.md
src/metrics/index_definitions.go
src/postgresql.go

Previously, the `quote_ident` was causing problems on some systems. 
TODO:

Fix index collection issue

---

CHANGELOG.md
src/connection/pgsql_connection.go
src/connection/pgsql_connection_mock.go
src/metrics/metrics.go
src/metrics/metrics_test.go
src/postgresql.go
vendor/github.com/newrelic/infra-integrations-sdk/args/args.go
vendor/github.com/newrelic/infra-integrations-sdk/data/metric/metrics.go
vendor/github.com/newrelic/infra-integrations-sdk/integration/entity.go
vendor/github.com/newrelic/infra-integrations-sdk/integration/entity_id.go
vendor/github.com/newrelic/infra-integrations-sdk/integration/integration.go
vendor/vendor.json

Update SDK
Prefix entity namespaces
Make entity keys more unique

Unique keys

---

Makefile-docker.mk
src/collection/collection_test.go

Add a detailed description and purpose of your changes.
Link the issue it solves (if there is one).

Bump docker version and fix formatting

---

Makefile-package.mk

Add a detailed description and purpose of your changes.
Link the issue it solves (if there is one).

Tarball makefile target and remove NRJMX dependency

---

CHANGELOG.md
pkg/windows/nri-386-installer/Product.wxs.template
pkg/windows/nri-386-installer/nri-installer.wixproj
pkg/windows/nri-amd64-installer/Product.wxs.template
pkg/windows/nri-amd64-installer/nri-installer.wixproj
postgresql-win-definition.yml
src/metrics/metrics.go
src/metrics/version_test.go
src/postgresql.go
versioninfo.json.template
win_build.ps1
windows_set_version.ps1

Add resources necessary to build Windows MSI
Clean and format the code

add windows msi resources

---

src/args/argument_list.go
src/connection/pgsql_connection.go
src/metrics/metrics.go
src/metrics/metrics_test.go
src/postgresql.go

Add support for a custom metrics query 
Clean and format the code

Add custom query support

---

src/metrics/database_definitions.go
tests/testdata/jsonschema90.json
tests/testdata/jsonschema91.json
tests/testdata/jsonschema92.json

Adding MaxConnection metric to allow calculating percentage of free connections when used together with activeConnections
Closes #55

Max connections

---

.golangci.yml
CHANGELOG.md
postgresql-config.yml.k8s_sample
postgresql-config.yml.sample
src/args/argument_list.go
src/collection/collection.go
src/collection/collection_test.go
tests/postgresql_test.go

Adds Database ignore list configuration

---

build/.goreleaser.yml
postgresql-log.yml.example

Update OHI to include postgresql-log.yml.example file to ingest postgresql logs

add_postgresql_logs_example_yml

---

.github/workflows/prerelease.yml
.github/workflows/push_pr.yml

We now add projects from snyk dashboard
Notice that I modified the semgrep action config since it was changing the local semgrep file:
```
Changes not staged for commit:
(use "git add <file>..." to update what will be committed)
(use "git restore <file>..." to discard changes in working directory)
modified:   .semgrep.yml
Untracked files:
(use "git add <file>..." to include in what will be committed)
.semgrepignore
```
it caused the error: `Found pending changes in tracked files. Baseline scans runs require a clean git state.`
Not sure why previously the same action step was not changing files tracked by git

fix(ci/cd): removing snyk unused step

---

build/.goreleaser.yml
postgresql-config.yml.sample
postgresql-custom-query.yml.sample

updated the syntax of the custom query file to match versions 13 and 14 of postgres

updated custom query

---

src/collection/collection.go
src/metrics/database_definitions.go
src/metrics/database_definitions_test.go
src/metrics/index_definitions.go
src/metrics/metric_types.go
src/metrics/metrics_test.go
src/metrics/table_definitions.go

This PR addresses https://github.com/newrelic/nri-postgresql/issues/94
This also fixes an issue where only indexes for the first database in the list were reported
Clean up and enhance debug messages

NEWRELIC-3807 Fix multiple indexes issue

---

.github/.renovate.json5
.github/workflows/prerelease.yml
.github/workflows/push_pr.yml
.github/workflows/release.yml
.github/workflows/security.yml
.github/workflows/trigger_prerelease.yml
.gitignore
CHANGELOG.md
Makefile

~Blocked by: https://github.com/newrelic/coreint-automation/pull/13~

NR-101030: enable automatic release

---

CHANGELOG.md

Update CHANGELOG.md to simply re-release the integration

Re-release integration to support new distros

---

README.md

We are changing out vuln bounty program and so the URL has changed

Vuln reporting URL changed

---

CHANGELOG.md
src/metrics/metrics_test.go
src/metrics/pgbouncer_definitions.go
tests/README.md
tests/docker-compose-pgbouncer.yml

Testcases added for v1.23
Docker compose file added for setting up pgBouncer environment in the future.

Added support for pgBouncer v1.23

---

CHANGELOG.md

Pre release broke mid pipeline so re releasing with a the tag 2.17.1

Added changelog for v2.17.1

---

CHANGELOG.md
postgresql-config.yml.sample
src/args/argument_list.go
src/main.go
src/query-performance-monitoring/common-parameters/common_parameters.go
src/query-performance-monitoring/common-utils/common_helpers.go
src/query-performance-monitoring/common-utils/common_helpers_test.go
src/query-performance-monitoring/common-utils/constants.go
src/query-performance-monitoring/common-utils/query_fetch_helpers.go
src/query-performance-monitoring/common-utils/query_fetch_helpers_test.go
src/query-performance-monitoring/datamodels/performance_data_models.go
src/query-performance-monitoring/performance-metrics/blocking_sessions.go
src/query-performance-monitoring/performance-metrics/blocking_sessions_test.go
src/query-performance-monitoring/performance-metrics/individual_query_metrics.go
src/query-performance-monitoring/performance-metrics/individual_query_metrics_test.go
src/query-performance-monitoring/performance-metrics/slow_query_metrics.go
src/query-performance-monitoring/performance-metrics/slow_query_metrics_test.go
src/query-performance-monitoring/performance-metrics/wait_event_metrics.go
src/query-performance-monitoring/performance-metrics/wait_event_metrics_test.go
src/query-performance-monitoring/queries/queries.go
src/query-performance-monitoring/query_performance_main.go
src/query-performance-monitoring/validations/performance_metrics_validations.go
src/query-performance-monitoring/validations/performance_metrics_validations_test.go
tests/postgresqlperf_test.go

PR to merge RDS support and create a pre-release to dest_prefix location

Aws rds db monitoring

---

CHANGELOG.md
README.md

update `changelog.md` to fix bad release v2.17.2

docs: update changelog.md to fix bad release

---

CHANGELOG.md
postgresql-config.yml.sample
src/args/argument_list.go
src/query-performance-monitoring/common-parameters/common_parameters.go

Updated Query Monitoring threshold to 1ms

fix: Updated Query Monitoring threshold to 1ms
